// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "BackEndService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::social_network;

class BackEndServiceHandler : virtual public BackEndServiceIf {
 public:
  BackEndServiceHandler() {
    // Your initialization goes here
  }

  void ComposePost(const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type) {
    // Your implementation goes here
    printf("ComposePost\n");
  }

  void ReadUserTimeline(std::vector<Post> & _return, const int64_t user_id, const int32_t start, const int32_t stop) {
    // Your implementation goes here
    printf("ReadUserTimeline\n");
  }

  void Login(std::string& _return, const std::string& username, const std::string& password) {
    // Your implementation goes here
    printf("Login\n");
  }

  void RegisterUser(const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password) {
    // Your implementation goes here
    printf("RegisterUser\n");
  }

  void RegisterUserWithId(const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password, const int64_t user_id) {
    // Your implementation goes here
    printf("RegisterUserWithId\n");
  }

  void GetFollowers(std::vector<int64_t> & _return, const int64_t user_id) {
    // Your implementation goes here
    printf("GetFollowers\n");
  }

  void Unfollow(const int64_t user_id, const int64_t followee_id) {
    // Your implementation goes here
    printf("Unfollow\n");
  }

  void UnfollowWithUsername(const std::string& user_usernmae, const std::string& followee_username) {
    // Your implementation goes here
    printf("UnfollowWithUsername\n");
  }

  void Follow(const int64_t user_id, const int64_t followee_id) {
    // Your implementation goes here
    printf("Follow\n");
  }

  void FollowWithUsername(const std::string& user_usernmae, const std::string& followee_username) {
    // Your implementation goes here
    printf("FollowWithUsername\n");
  }

  void GetFollowees(std::vector<int64_t> & _return, const int64_t user_id) {
    // Your implementation goes here
    printf("GetFollowees\n");
  }

  void ReadHomeTimeline(std::vector<Post> & _return, const int64_t user_id, const int32_t start, const int32_t stop) {
    // Your implementation goes here
    printf("ReadHomeTimeline\n");
  }

  void UploadMedia(const std::string& filename, const std::string& data) {
    // Your implementation goes here
    printf("UploadMedia\n");
  }

  void GetMedia(std::string& _return, const std::string& filename) {
    // Your implementation goes here
    printf("GetMedia\n");
  }

  void RemovePosts(const int64_t user_id, const int32_t start, const int32_t stop) {
    // Your implementation goes here
    printf("RemovePosts\n");
  }

  void NoOp() {
    // Your implementation goes here
    printf("NoOp\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<BackEndServiceHandler> handler(new BackEndServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new BackEndServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

